# Generated by Django 4.0 on 2022-05-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_price_product_price_avg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name_long_shop',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_short_shop',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_avg',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sallers',
            field=models.IntegerField(null=True),
        ),
    ]
