# Generated by Django 4.0 on 2022-05-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_name_long_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='links',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
